-- External Data Dependencies (per Sara, 2026-09-07): design inputs that come
-- from OUTSIDE the drawing set - utility fault current, hydrant flow test
-- data, service coordination, owner-provided data. The review searches the
-- project log for the evidence; when it is NOT on record the finding is
-- raised FOR THE USER TO ANSWER (attach the data or state its status), and
-- the answer lands as the ledger row's note. Rows carry source='lesson' -
-- policy additions after the seed, added without a deploy. Inserts are in
-- the applied migration (idempotent, on conflict do nothing).
insert into public.pms_qa_checklist (item_id, template_id, section, sort, text, details, automation, automation_hint, source, added_by) values
('qa-300','deliverable-qa','External Data Dependencies',1290,'Verify available fault current data from the utility is on record and matches the value cited on the electrical drawings.','["Search the project log (emails, documents) for the utility coordination / fault current letter.","Search the drawings for the cited value (AVAILABLE FAULT CURRENT / AIC).","If NOT on record: flag for the user to attach or enter the data - the answer is recorded as the ledger note."]'::jsonb,'assisted','search_drawings for AVAILABLE FAULT CURRENT / AIC values; search_emails + find_document for the utility coordination letter; absent -> ledger finding for the user to answer','lesson','sara.arias@setty.com'),
('qa-301','deliverable-qa','External Data Dependencies',1300,'Verify hydrant flow test data is on record, current, and matches the fire protection hydraulic calculation basis.','["Flow test typically must be recent (often within 12 months at bid) - check the test date.","Compare static/residual/flow values against the hydraulic calc basis on the FP drawings.","If NOT on record: flag for the user to attach or enter the data."]'::jsonb,'assisted','search_drawings for FLOW TEST / STATIC / RESIDUAL on FP sheets; search_emails + find_document for the test report; absent -> ledger finding for the user to answer','lesson','sara.arias@setty.com'),
('qa-302','deliverable-qa','External Data Dependencies',1310,'Verify utility service coordination is on record for every service shown: electric service confirmation, gas availability, water/sewer availability.','["Match services shown on the drawings (service entrances, gas equipment, new water/sewer connections) against coordination records in the log.","If NOT on record: flag per service for the user to attach or enter the status."]'::jsonb,'assisted','Derive required services from the drawings (search_drawings); search_emails/find_document for ConEd/National Grid/DEP coordination; absent -> ledger finding per service','lesson','sara.arias@setty.com'),
('qa-303','deliverable-qa','External Data Dependencies',1320,'Verify any other design input sourced outside the drawing set (owner-provided data, existing record drawings relied on, survey/geotech where referenced) is on record with its source and date.',null,'assisted','Where a sheet cites external data, find the source document in the project log; absent -> ledger finding naming what is relied on but not on record','lesson','sara.arias@setty.com')
on conflict (item_id) do nothing;
