-- QA Deliverables Checklist as CONTENT (was code-defined in SettyPMS.html's
-- CHECKLIST_TEMPLATES). One row per item; the seed mirrors the app template
-- verbatim, so item_ids stay stable and per-project check-off state in
-- project.checklists keeps working. `automation` says what the coordination
-- review can do with each item TODAY:
--   auto     - the connector checks it mechanically (drawing index, schedule
--              reader, tag registry, text search); automation_hint names how
--   assisted - Claude gathers evidence (text hits, rendered regions) and
--              flags exceptions; a human confirms
--   manual   - engineering/plot judgment, human only
-- `source` tracks provenance: 'seed' now; 'lesson' rows are added over time
-- from lessons learned, which is how the review gets smarter without a
-- deploy. Read for all authenticated (the app and the connector serve it);
-- writes admin-only, same posture as pms_capability_catalog / pms_regions.

create table if not exists public.pms_qa_checklist (
  item_id         text primary key,
  template_id     text not null default 'deliverable-qa',
  section         text not null,
  sort            int  not null default 0,
  text            text not null,
  details         jsonb,
  automation      text not null default 'assisted' check (automation in ('auto','assisted','manual')),
  automation_hint text,
  enabled         boolean not null default true,
  source          text not null default 'seed',
  added_by        text,
  added_at        timestamptz not null default now()
);

alter table public.pms_qa_checklist enable row level security;
drop policy if exists qa_checklist_read on public.pms_qa_checklist;
create policy qa_checklist_read on public.pms_qa_checklist for select to authenticated using (true);
drop policy if exists qa_checklist_admin_all on public.pms_qa_checklist;
create policy qa_checklist_admin_all on public.pms_qa_checklist for all
  using (is_pms_admin()) with check (is_pms_admin());
insert into public.pms_qa_checklist (item_id, template_id, section, sort, text, details, automation, automation_hint) values
('qa-001','deliverable-qa','General Document Verification',10,'Verify the project name, address, block/lot, client name, and project number match exactly on:','["Cover sheet","Title blocks","Specifications","Narratives","Calculations","Reports"]'::jsonb,'auto','search_drawings for the project name/number/address strings; extract_sheet_index + title-block fields from the drawing index'),
('qa-002','deliverable-qa','General Document Verification',20,'Verify all disciplines are using the same issue date and revision date.',null,'auto','drawing index title-block revision_date across disciplines (pms_drawing_text)'),
('qa-003','deliverable-qa','General Document Verification',30,'Verify all sheet numbers listed on the drawing index are included in the PDF set.',null,'auto','extract_sheet_index (drawing list) vs sheets actually indexed in the set'),
('qa-004','deliverable-qa','General Document Verification',40,'Verify no sheets are duplicated, skipped, or mislabeled.',null,'auto','sheet_no list from the drawing index: duplicates, gaps, mislabels'),
('qa-005','deliverable-qa','General Document Verification',50,'Verify north arrows point in the same direction on all floor plans.',null,'assisted',null),
('qa-006','deliverable-qa','General Document Verification',60,'Verify floor plans from all disciplines use the same orientation and architectural background.',null,'manual',null),
('qa-007','deliverable-qa','General Document Verification',70,'Verify all plans, sections, details, and elevations include drawing scales.',null,'assisted',null),
('qa-008','deliverable-qa','General Document Verification',80,'Verify all required narratives, specifications, calculations, reports, and supporting documents are included in the submission package.',null,'assisted',null),
('qa-009','deliverable-qa','General Document Verification',90,'Verify all calculations are signed, dated, and saved in the project folder.',null,'manual',null),
('qa-010','deliverable-qa','General Document Verification',100,'Verify project phase is correctly identified throughout the documents:','["SD","DD","CD","Permit","Bid","Record Drawings","Bulletin","Addendum"]'::jsonb,'assisted',null),
('qa-011','deliverable-qa','General Document Verification',110,'Verify code versions match across all disciplines and match architect''s code summary.',null,'auto','search_drawings for code-year strings (e.g. ''2020 ECCCNYS'', ''NYC BC 2022'') across disciplines'),
('qa-020','deliverable-qa','Drawing Graphics & Presentation',120,'Review plotted PDF at full size and half size. Verify all text remains readable at half size.','["Recommended minimum plotted text heights:","Sheet titles: 3/16\"","Major notes: 1/8\"","General notes/dimensions: 3/32\" minimum"]'::jsonb,'assisted',null),
('qa-021','deliverable-qa','Drawing Graphics & Presentation',130,'Verify text does not overlap:','["Walls","Ductwork","Piping","Conduit","Equipment","Other text"]'::jsonb,'assisted',null),
('qa-022','deliverable-qa','Drawing Graphics & Presentation',140,'Verify notes and dimensions do not extend outside sheet borders.',null,'assisted',null),
('qa-023','deliverable-qa','Drawing Graphics & Presentation',150,'Verify lineweights are visually consistent:','["Existing work lighter than new work","Demolition distinct from new work","Major equipment darker than background systems"]'::jsonb,'manual',null),
('qa-024','deliverable-qa','Drawing Graphics & Presentation',160,'Verify hidden lines, centerlines, and demolition graphics are visually distinguishable.',null,'manual',null),
('qa-025','deliverable-qa','Drawing Graphics & Presentation',170,'Verify all detail callouts reference the correct detail and sheet number.',null,'assisted',null),
('qa-026','deliverable-qa','Drawing Graphics & Presentation',180,'Verify section cuts and matchlines reference continuation sheets correctly.',null,'assisted',null),
('qa-027','deliverable-qa','Drawing Graphics & Presentation',190,'Verify all schedules fit fully within the drawing sheet and are not cut off during plotting.',null,'assisted',null),
('qa-028','deliverable-qa','Drawing Graphics & Presentation',200,'Verify viewport titles match the plans/details shown.',null,'assisted',null),
('qa-029','deliverable-qa','Drawing Graphics & Presentation',210,'Verify legends and abbreviations include all symbols used on the drawings.',null,'assisted',null),
('qa-030','deliverable-qa','Drawing Graphics & Presentation',220,'Verify keynote numbering is sequential and no keynote references are missing.',null,'assisted',null),
('qa-031','deliverable-qa','Drawing Graphics & Presentation',230,'Verify no stray drafting lines, duplicate notes, empty text boxes, visible construction geometry, or CAD artifacts remain.',null,'manual',null),
('qa-032','deliverable-qa','Drawing Graphics & Presentation',240,'Search drawings/specifications for unresolved placeholders and verify they are removed or clarified:','["TBD","VERIFY","NIC","XXX","Lorem Ipsum","By Others","Insert Here"]'::jsonb,'auto','search_drawings for TBD / VERIFY / XXX / ''By Others'' / ''Insert Here'' / Lorem'),
('qa-033','deliverable-qa','Drawing Graphics & Presentation',250,'Verify all sheets plot correctly without:','["Missing xrefs","Shifted backgrounds","Corrupt graphics","Blank viewports","Missing raster images"]'::jsonb,'manual',null),
('qa-034','deliverable-qa','Drawing Graphics & Presentation',260,'Verify title blocks are complete and consistent on all sheets.',null,'assisted',null),
('qa-040','deliverable-qa','Room Names / Architectural Coordination',270,'Verify room names and room numbers match architectural drawings exactly.',null,'assisted',null),
('qa-041','deliverable-qa','Room Names / Architectural Coordination',280,'Verify room usage shown on MEPFP drawings matches architectural room function.','["Examples:","Electrical rooms","IT rooms","Mechanical rooms","Toilet rooms","Storage rooms"]'::jsonb,'assisted',null),
('qa-042','deliverable-qa','Room Names / Architectural Coordination',290,'Verify MEPFP equipment is not located in architecturally inappropriate spaces unless intentional.','["Examples:","No electrical panels in toilet rooms","No access panels centered in decorative ceilings","No exposed piping in finished feature spaces unless intentional"]'::jsonb,'assisted',null),
('qa-050','deliverable-qa','Equipment Coordination',300,'Compare MEPFP plans and verify major equipment appears in the same location on all disciplines.',null,'assisted',null),
('qa-051','deliverable-qa','Equipment Coordination',310,'Verify equipment shown on one discipline has corresponding utility connections shown on other disciplines.','["Examples:","HVAC equipment → power + condensate + controls","Pumps → power + drains + controls","Water heaters → power/gas + venting + drains","Fire pump → power + fire alarm + drains"]'::jsonb,'assisted',null),
('qa-052','deliverable-qa','Equipment Coordination',320,'Verify equipment tags match exactly between:','["Plans","Schedules","Details","Specifications","Control diagrams"]'::jsonb,'auto','find_equipment tag mode per tag: plans/schedules/details presence; read_drawing_schedule for the schedule side'),
('qa-053','deliverable-qa','Equipment Coordination',330,'Verify all scheduled equipment appears on plans.',null,'auto','read_drawing_schedule rows vs find_equipment sheet appearances (scheduled but never on plans)'),
('qa-054','deliverable-qa','Equipment Coordination',340,'Verify no equipment appears on plans without being included on schedules.',null,'auto','find_equipment enumeration vs schedule rows (on plans but never scheduled)'),
('qa-055','deliverable-qa','Equipment Coordination',350,'Verify manufacturer names and basis-of-design information are coordinated throughout the documents.',null,'assisted',null),
('qa-060','deliverable-qa','Electrical Voltage / Power Coordination',360,'Verify electrical characteristics for equipment are coordinated between mechanical/plumbing schedules and electrical drawings.','["Locate equipment on the mechanical/plumbing schedule.","Identify: Voltage, Phase, MCA, MOP/MOCP","Locate the same equipment on electrical drawings and panel schedules.","Verify voltages match exactly (480V → 480V panel, 208V → 120/208V panel, no 120V → 480V).","Verify phases match: single-phase → single-phase breaker, three-phase → 3-pole breaker.","Verify no equipment appears on mechanical/plumbing schedules without electrical connection shown.","Verify no electrical connections exist for equipment no longer shown."]'::jsonb,'auto','read_drawing_schedule on M/P schedules (V/Ph/MCA/MOCP columns) vs the same tags on E sheets and panel schedules'),
('qa-061','deliverable-qa','Electrical Voltage / Power Coordination',370,'Verify disconnect switches are shown where required for major mechanical equipment.',null,'assisted',null),
('qa-062','deliverable-qa','Electrical Voltage / Power Coordination',380,'Verify electrical panel names and voltages are coordinated consistently throughout drawings.',null,'assisted',null),
('qa-063','deliverable-qa','Electrical Voltage / Power Coordination',390,'Verify electrical panels are not shown recessed into fire-rated walls unless specifically detailed and permitted.',null,'assisted',null),
('qa-070','deliverable-qa','Electrical Clearances',400,'Verify minimum electrical working clearance in front of panels, switchboards, MCCs, transformers, and disconnects.','["Minimum required clearances:","Depth: 3''-0\" minimum","Width: 30\" minimum or equipment width","Headroom: 6''-6\" minimum"]'::jsonb,'assisted',null),
('qa-071','deliverable-qa','Electrical Clearances',410,'Verify clearance spaces remain free of:','["Piping","Ductwork","Equipment","Stored items","Door swings"]'::jsonb,'assisted',null),
('qa-072','deliverable-qa','Electrical Clearances',420,'Verify no domestic water, sanitary, condensate, or unrelated piping passes above electrical equipment.',null,'assisted',null),
('qa-073','deliverable-qa','Electrical Clearances',430,'Verify electrical equipment is not located:','["Inside bathrooms","Inside closets without access","Behind doors"]'::jsonb,'assisted',null),
('qa-080','deliverable-qa','Ceiling Coordination',440,'Overlay reflected ceiling plans and verify lighting, diffusers, sprinkler heads, speakers, cameras, access panels, and smoke detectors do not overlap.',null,'assisted',null),
('qa-081','deliverable-qa','Ceiling Coordination',450,'Verify sprinkler heads are not centered directly on:','["Light fixtures","Diffusers","Ceiling speakers"]'::jsonb,'assisted',null),
('qa-082','deliverable-qa','Ceiling Coordination',460,'Verify access panels are not directly adjacent to lights or diffusers.','["Preferred spacing: approximately 12\" minimum separation where possible"]'::jsonb,'assisted',null),
('qa-083','deliverable-qa','Ceiling Coordination',470,'Verify ceiling devices are centered within ceiling tiles where ACT ceilings are used.',null,'assisted',null),
('qa-084','deliverable-qa','Ceiling Coordination',480,'Verify ceiling-mounted devices do not conflict with:','["Structural beams","Soffits","Decorative ceiling elements"]'::jsonb,'assisted',null),
('qa-085','deliverable-qa','Ceiling Coordination',490,'Verify ceiling spaces appear reasonably coordinated.','["General rule:","Large duct mains routed first / highest priority","Smaller piping/conduit routed around larger systems"]'::jsonb,'manual',null),
('qa-086','deliverable-qa','Ceiling Coordination',500,'Verify ceiling congestion does not appear physically impossible in corridors or low ceiling spaces.',null,'manual',null),
('qa-090','deliverable-qa','Equipment Access & Maintenance Clearances',510,'Verify all major equipment has working/service clearance.','["Typical minimum clearances:","Electrical panels: 36\" front clearance","AHUs: 36\" service side clearance","Pumps: 24\"-36\" around motor side","Boilers/water heaters: 30\"-36\" front clearance"]'::jsonb,'assisted',null),
('qa-091','deliverable-qa','Equipment Access & Maintenance Clearances',520,'Verify equipment doors can fully open without hitting walls or adjacent equipment.',null,'assisted',null),
('qa-092','deliverable-qa','Equipment Access & Maintenance Clearances',530,'Verify filters, motors, belts, coils, and access doors can be removed without demolition.',null,'assisted',null),
('qa-093','deliverable-qa','Equipment Access & Maintenance Clearances',540,'Verify access panels are provided above hard ceilings for:','["Dampers","Valves","VAV boxes","Fire/smoke dampers","Cleanouts"]'::jsonb,'assisted',null),
('qa-094','deliverable-qa','Equipment Access & Maintenance Clearances',550,'Verify access panel sizes are appropriate:','["12\"x12\" minimum small valves/devices","18\"x18\" preferred for VAVs/fire dampers"]'::jsonb,'assisted',null),
('qa-095','deliverable-qa','Equipment Access & Maintenance Clearances',560,'Verify equipment replacement paths appear possible through:','["Doors","Corridors","Roof hatches","Stairs"]'::jsonb,'assisted',null),
('qa-100','deliverable-qa','Shafts / Risers / Penetrations',570,'Verify shafts align vertically floor-to-floor.',null,'assisted',null),
('qa-101','deliverable-qa','Shafts / Risers / Penetrations',580,'Verify shaft sizes appear sufficient for systems shown.',null,'assisted',null),
('qa-102','deliverable-qa','Shafts / Risers / Penetrations',590,'Verify major penetrations are coordinated between disciplines.',null,'assisted',null),
('qa-103','deliverable-qa','Shafts / Risers / Penetrations',600,'Verify penetrations are not shown through structural beams unless specifically coordinated.',null,'assisted',null),
('qa-104','deliverable-qa','Shafts / Risers / Penetrations',610,'Verify fire-rated penetrations include:','["Dampers where required","Firestopping notes/details"]'::jsonb,'assisted',null),
('qa-110','deliverable-qa','Roof Coordination',620,'Verify rooftop equipment locations match architectural roof plans.',null,'assisted',null),
('qa-111','deliverable-qa','Roof Coordination',630,'Verify rooftop equipment does not block:','["Roof hatches","Ladders","Egress paths","Roof drains"]'::jsonb,'assisted',null),
('qa-112','deliverable-qa','Roof Coordination',640,'Verify minimum walking/service path around rooftop equipment.','["36\" preferred minimum"]'::jsonb,'assisted',null),
('qa-113','deliverable-qa','Roof Coordination',650,'Verify rooftop equipment does not conflict with:','["Skylights","PV arrays","Green roofs","Architectural screens"]'::jsonb,'assisted',null),
('qa-114','deliverable-qa','Roof Coordination',660,'Verify exhaust fans and outside air intakes are separated where possible.','["10''-0\" minimum where practical"]'::jsonb,'assisted',null),
('qa-115','deliverable-qa','Roof Coordination',670,'Verify plumbing vents terminate away from outside air intakes.','["10''-0\" minimum where practical"]'::jsonb,'assisted',null),
('qa-120','deliverable-qa','Demolition / Renovation Coordination',680,'Verify demolition work is graphically distinct from new work.',null,'assisted',null),
('qa-121','deliverable-qa','Demolition / Renovation Coordination',690,'Verify existing, demolished, relocated, and new work are clearly identified.',null,'assisted',null),
('qa-122','deliverable-qa','Demolition / Renovation Coordination',700,'Verify "existing to remain" equipment is not shown demolished elsewhere.',null,'assisted',null),
('qa-123','deliverable-qa','Demolition / Renovation Coordination',710,'Verify tie-ins to existing systems are clearly identified.',null,'assisted',null),
('qa-124','deliverable-qa','Demolition / Renovation Coordination',720,'Verify field verification notes are included where existing conditions are uncertain.',null,'assisted',null),
('qa-125','deliverable-qa','Demolition / Renovation Coordination',730,'Review demolition plans and renovation notes to determine whether existing systems serving occupied areas are being modified or disconnected.',null,'assisted',null),
('qa-126','deliverable-qa','Demolition / Renovation Coordination',740,'Verify drawings identify if temporary systems are required during construction:','["Temporary power","Temporary HVAC","Temporary water service","Temporary fire protection service"]'::jsonb,'assisted',null),
('qa-127','deliverable-qa','Demolition / Renovation Coordination',750,'Verify planned shutdowns are identified where systems connect to existing building systems.','["Examples:","Electrical tie-ins","Water shutdowns","Sprinkler shutdowns","Fire alarm tie-ins"]'::jsonb,'assisted',null),
('qa-128','deliverable-qa','Demolition / Renovation Coordination',760,'Verify phased work areas are clearly identified where applicable.',null,'assisted',null),
('qa-129','deliverable-qa','Demolition / Renovation Coordination',770,'Verify notes require contractor coordination with owner before utility shutdowns where appropriate.',null,'assisted',null),
('qa-140','deliverable-qa','Drawings / Specifications Coordination',780,'Verify schedules match drawings:','["Voltage","Airflow","Pipe sizes","GPM","BTUH","Circuit information"]'::jsonb,'assisted',null),
('qa-141','deliverable-qa','Drawings / Specifications Coordination',790,'Verify drawing notes and specifications do not conflict.',null,'assisted',null),
('qa-142','deliverable-qa','Drawings / Specifications Coordination',800,'Verify specification section numbers and titles are correct.',null,'auto','search_drawings + read_document(find:) for spec section numbers cited on drawings vs the project manual'),
('qa-143','deliverable-qa','Drawings / Specifications Coordination',810,'Verify unused specification options and placeholder text are removed.',null,'assisted',null),
('qa-144','deliverable-qa','Drawings / Specifications Coordination',820,'Verify delegated design items are clearly identified.',null,'assisted',null),
('qa-145','deliverable-qa','Drawings / Specifications Coordination',830,'Verify trade responsibility boundaries are clearly identified where scope overlap may occur.',null,'assisted',null),
('qa-146','deliverable-qa','Drawings / Specifications Coordination',840,'Verify alternates, allowances, deferred submittals, and owner-furnished equipment are clearly identified.',null,'assisted',null),
('qa-150','deliverable-qa','Optional — NYC DOB / Agency Review Items',850,'Verify sheet numbering follows NYC DOB discipline conventions where applicable:','["A = Architectural","M = Mechanical","E = Electrical","P = Plumbing","FP = Fire Protection","FA = Fire Alarm","EN = Energy"]'::jsonb,'assisted',null),
('qa-151','deliverable-qa','Optional — NYC DOB / Agency Review Items',860,'Verify sheet numbering format is consistent throughout the set.','["Example: M001.00 / M101.00 / M601.00"]'::jsonb,'auto','sheet_no list from the drawing index: numbering format consistency'),
('qa-152','deliverable-qa','Optional — NYC DOB / Agency Review Items',870,'Verify required NYC Special Inspections are identified in drawings or specifications.',null,'assisted',null),
('qa-153','deliverable-qa','Optional — NYC DOB / Agency Review Items',880,'Verify Energy Code Progress Inspections are referenced where required.',null,'assisted',null),
('qa-154','deliverable-qa','Optional — NYC DOB / Agency Review Items',890,'Verify required DOB notes are included where applicable.',null,'assisted',null),
('qa-155','deliverable-qa','Optional — NYC DOB / Agency Review Items',900,'Verify Con Edison coordination notes are included where service modifications occur.',null,'assisted',null),
('qa-156','deliverable-qa','Optional — NYC DOB / Agency Review Items',910,'Verify FDNY coordination notes are included where applicable.',null,'assisted',null),
('qa-157','deliverable-qa','Optional — NYC DOB / Agency Review Items',920,'Verify agency-specific title blocks and submission requirements are included where required:','["DOB","SCA","DASNY","SUCF","PANYNJ","EDC"]'::jsonb,'assisted',null),
('qa-200','deliverable-qa','Commonly Missed / High-Risk Coordination Items',930,'Verify room names and room numbers are consistent between all disciplines and architectural backgrounds.','["Common issue: Architect updates room numbers late in project and MEP sheets are not refreshed."]'::jsonb,'assisted',null),
('qa-201','deliverable-qa','Commonly Missed / High-Risk Coordination Items',940,'Verify all equipment scheduled on plans has a tag shown next to the equipment on floor plans.','["Common issue: Equipment shown graphically but not tagged, creating confusion during submittals and CA."]'::jsonb,'auto','find_equipment: scheduled tags with no plan-sheet appearance'),
('qa-202','deliverable-qa','Commonly Missed / High-Risk Coordination Items',950,'Verify all equipment tags shown on plans exist on schedules.','["Common issue: Deleted equipment remains in schedules."]'::jsonb,'auto','find_equipment: plan tags missing from schedules'),
('qa-203','deliverable-qa','Commonly Missed / High-Risk Coordination Items',960,'Verify no duplicate equipment tags exist.','["Examples:","Two EF-1 tags","Duplicate panel names","Duplicate VAV numbers"]'::jsonb,'auto','find_equipment enumeration: duplicate-tag detection across sheets'),
('qa-204','deliverable-qa','Commonly Missed / High-Risk Coordination Items',970,'Verify ceiling heights appear reasonable where large ductwork crosses corridors or beams.','["General rule: If duct mains, piping, lighting, and structure all occupy the same space, flag for review."]'::jsonb,'assisted',null),
('qa-205','deliverable-qa','Commonly Missed / High-Risk Coordination Items',980,'Verify thermostats, switches, and wall devices are not located behind doors, casework, TVs/displays, or inside millwork.','["Preferred mounting heights:","Thermostats: approximately 48\" AFF","Light switches: approximately 44\"-48\" AFF"]'::jsonb,'assisted',null),
('qa-206','deliverable-qa','Commonly Missed / High-Risk Coordination Items',990,'Verify access panels are shown for fire/smoke dampers, control valves, VAV boxes, cleanouts, and balancing dampers.','["Common issue: Device exists above hard ceiling but no access panel shown."]'::jsonb,'assisted',null),
('qa-207','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1000,'Verify plumbing cleanouts are not hidden behind millwork, inside inaccessible chases, or above hard ceilings without access.',null,'assisted',null),
('qa-208','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1010,'Verify floor drains are located in rooms likely to require drainage.','["Examples: Mechanical rooms, Boiler rooms, Pump rooms, AHU rooms","Common issue: Equipment with condensate or relief discharge but no nearby drain."]'::jsonb,'assisted',null),
('qa-209','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1020,'Verify electrical panels are not blocked by:','["Doors","Casework","Plumbing fixtures","Ductwork"]'::jsonb,'assisted',null),
('qa-210','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1030,'Verify no ductwork or piping passes directly through structural beams unless intentionally coordinated.',null,'assisted',null),
('qa-211','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1040,'Verify fire/smoke dampers are shown where ducts pass through fire-rated walls or shafts.','["Common issue: Architect changes wall rating late in project."]'::jsonb,'assisted',null),
('qa-212','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1050,'Verify shafts continue vertically floor-to-floor and are not accidentally offset.',null,'assisted',null),
('qa-213','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1060,'Verify equipment requiring outside air or exhaust connections actually has duct routing shown.','["Common issue: Equipment scheduled but no duct connection shown."]'::jsonb,'assisted',null),
('qa-214','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1070,'Verify mechanical equipment requiring condensate drainage has condensate piping shown.','["Examples: FCUs, VRF indoor units, AHUs, Split systems"]'::jsonb,'assisted',null),
('qa-215','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1080,'Verify roof drains, overflow drains, and plumbing vents are coordinated with rooftop equipment.','["Common issue: Equipment placed directly over drain locations."]'::jsonb,'assisted',null),
('qa-216','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1090,'Verify rooftop equipment does not create inaccessible roof corners or block maintenance pathways.',null,'assisted',null),
('qa-217','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1100,'Verify louvers shown on floor plans generally align with architectural elevations.','["Common issue: MEP adds louvers but elevations are never updated."]'::jsonb,'assisted',null),
('qa-218','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1110,'Verify electrical panel schedules are balanced reasonably between phases.','["General rule: Do not allow one phase to be overloaded significantly compared to others."]'::jsonb,'assisted',null),
('qa-219','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1120,'Verify panel schedules do not contain spare circuits feeding equipment, duplicate circuit numbers, or empty descriptions for active circuits.',null,'auto','read_drawing_schedule on panel schedules: duplicate circuit numbers, empty descriptions, spares feeding loads'),
('qa-220','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1130,'Verify lighting fixture types shown on plans match fixture schedule.','["Common issue: Fixture renamed on one sheet only."]'::jsonb,'auto','read_drawing_schedule (fixture schedule) vs fixture types found by search_drawings on plans'),
('qa-221','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1140,'Verify emergency lighting and exit signs appear in:','["Exit corridors","Stairs","Egress paths"]'::jsonb,'assisted',null),
('qa-222','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1150,'Verify sprinkler heads are not shown directly centered on diffusers, light fixtures, or ceiling speakers.',null,'assisted',null),
('qa-223','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1160,'Verify wall-mounted devices are not placed directly on glazing, mirrors, or movable partitions.',null,'assisted',null),
('qa-224','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1170,'Verify all dimensions critical to MEPFP coordination are shown where needed.','["Examples: Large equipment pads, Utility clearances, Shaft dimensions, Major sleeves"]'::jsonb,'assisted',null),
('qa-225','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1180,'Verify demolition plans clearly indicate whether existing equipment is:','["Removed","Relocated","Reused","Remains in place","Common issue: Contractor confusion leading to unintended demolition."]'::jsonb,'assisted',null),
('qa-226','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1190,'Verify there are no disconnected systems shown graphically.','["Examples:","Ducts ending without connection","Piping not connecting to equipment","Conduit not terminating anywhere"]'::jsonb,'assisted',null),
('qa-227','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1200,'Verify all abbreviations used on drawings appear in the abbreviation list.',null,'assisted',null),
('qa-228','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1210,'Verify all symbols shown on drawings appear in legends.',null,'assisted',null),
('qa-229','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1220,'Verify equipment schedules do not contain placeholder values.','["Examples: \"TBD\" airflow, \"Verify Voltage\", Missing capacities"]'::jsonb,'auto','read_drawing_schedule: cells containing TBD / VERIFY / blank capacities'),
('qa-230','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1230,'Verify sequence of operation references match actual equipment shown.','["Common issue: Sequences copied from prior project."]'::jsonb,'assisted',null),
('qa-231','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1240,'Verify no notes reference incorrect project names or prior project information.','["Common issue: Copied details/specifications from previous job."]'::jsonb,'auto','search_drawings for prior-project names (from the firm''s project list) appearing in this set'),
('qa-232','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1250,'Verify disciplines are using the latest architectural background.','["Common issue: One discipline working from outdated floor plan."]'::jsonb,'assisted',null),
('qa-233','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1260,'Verify no dimensions, tags, or notes are located outside printable drawing area.',null,'assisted',null),
('qa-234','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1270,'Verify clouded revisions are actually revised.','["Common issue: Cloud shown but no change made."]'::jsonb,'assisted',null),
('qa-235','deliverable-qa','Commonly Missed / High-Risk Coordination Items',1280,'Verify all sheets have consistent spelling, capitalization, and naming conventions.','["Examples: \"Elec Room\" vs \"Electrical Room\", \"Toilet Room\" vs \"Restroom\""]'::jsonb,'assisted',null)
on conflict (item_id) do nothing;
